on: [push]
name: Helloworld
jobs:
  build:
    name: Testingjobs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: ls > hello.txt
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: hello.txt
